apiVersion: batch/v1
kind: CronJob
metadata:
  name: iss-poller
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: iss-poller
              image: image-registry.openshift-image-registry.svc:5000/data-engineering-workshops-61cf54/iss-poller:latest
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "50m"
                limits:
                  memory: "128Mi"
                  cpu: "200m"
              env:
                - name: DB_HOST
                  value: "postgres"
                - name: DB_PORT
                  value: "5432"
                - name: DB_NAME
                  value: "issdb"
                - name: DB_USER
                  value: "issuser"
                - name: DB_PASS
                  value: "postgres"
          restartPolicy: OnFailure
