apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: image-registry.openshift-image-registry.svc:5000/openshift/postgresql:13-el8
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: POSTGRESQL_DATABASE
              value: "issdb"
            - name: POSTGRESQL_USER
              value: "issuser"
            - name: POSTGRESQL_PASSWORD
              value: "postgres"
            - name: POSTGRESQL_ADMIN_PASSWORD
              value: "postgres"
            - name: PGDATA
              value: "/var/lib/pgsql/data/pgdata"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/pgsql/data
            - name: init-script
              mountPath: /opt/app-root/src/postgresql-init
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: init-script
          configMap:
            name: postgres-init
